---
title: "___"
author: "___"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

<!--# Cette balise est un commentaire. -->

<!--% Cette balise est une consigne. Ne jamais modifier ni déplacer les consignes dans le document! -->

<!--% Ajoutez un titre et votre nom.-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = F)
SciViews::R("model", lang = "fr")
```

## Introduction et but

<!--# Introduction et but ont été réduits à leur plus simple expression en une seule phrase, mais normalement cette section est plus détaillée (ce n'est pas le but de l'exercice ici) ! -->

L'étude globale souhaite modéliser l'age des ormeaux sur base de mesures morphologiques. Ce carnet de notes s'intéresse à l'évolution de la masse en fonction de la longueur de la coquille.

## Résultats

<!--% Importez les données `abalone` générées depuis le script R.-->

```{r read}
abalone <- read()
```

### Description des données

<!--% Réalisez un nuage de points de la variable `whole_weight` en fonction de la variable `length`. -->

```{r plot}

```

<!--% Décrivez le graphique ci-dessus en 2 à 3 phrases.-->

<!--% Utilisez le chunk ci-dessous afin de transformez les données, si nécessaire-->

```{r mutate}

```

<!--% Proposez un tableau supplémentaire.-->

```{r tab}

```

<!--% Décrivez le tableau ci-dessus en 2 à 3 phrases.-->

### Modélisation de la masse

<!--% Utilisez la fonction `lm()` afin de calculer la régression linéaire demandée. Placez le résultat dans une variable `lm.`. Affichez le droite de régression sur le nuage de point. -->

```{r lm}
lm. <- ___
chart(___)
```

<!--% Écrivez l'équation mathématique de ce modèle (paramétrisation du modèle) en utilisant la syntaxe LaTeX ci-dessous. -->

$$___equation___$$

<!--% Proposez un résumé de votre modèle avec la fonction `summary()` appliquée sur votre objet `lm.`.-->

```{r summary}

```

<!--% Décrivez le résultat du résumé de l'objet `lm.` en 3 à 4 phrases. Soyez complet ! -->

<!--% Étudiez la distribution homogène des résidus de votre modèle. -->

```{r resid1}

```

<!--% Décrivez le graphique ci-dessus en 2 à 3 phrases. Soyez complet ! -->

<!--% Vérifiez la normalité des résidus de votre modèle. -->

```{r resid2}

```

<!--% Décrivez le graphique ci-dessus en 2 à 3 phrases. Soyez complet ! -->

<!--% Étudiez la distribution des résidus standardisés. -->

```{r resid3}

```

<!--% Décrivez le graphique ci-dessus en 2 à 3 phrases. Soyez complet ! -->

<!--% Étudiez l’influence des individus sur la régression linéaire grâce à la distance de Cook. -->

```{r resid4}

```

<!--% Décrivez le graphique ci-dessus en 2 à 3 phrases. Soyez complet ! -->

## Discussion et conclusion

<!--% Selon vous, est-ce que ce modèle représente correctement vos données. Répondez en 4 à 6 lignes. Énoncez éventuellement des pistes d'amélioration du modèle dans vos conclusions. -->
